### PR TITLE
pulp init: Refuse to overwrite anything without --force.

### LINKED ISSUE #73: pulp init silently overwrites existing files
To reproduce just do `pulp init` in any existing repo. Your `bower.json` and `src/Main.purs` would be overwritten.

This might end up very sad for someone. It's not just about being fool-proof, first writing something in `src/Main.purs` and only then initiating the project is quite a common scenario (at least for me).

### PR DESCRIPTION
**Pull request by damncabbage**
Extends the existing `bower.json` check to cover the other files that get written out.

(Fixes #73.)

### CODE REVIEW

**Comment by damncabbage** [comment]
(Happy to take feedback on the style of this. The array-of-things-to-check irks me, but I can't think of a better way.)

**Comment by hdgarrood** [comment]
What irks you about the array-of-things-to-check? It feels like the right approach to me (although this may well just be due to a lack of imagination!)

**Comment by damncabbage** [comment]
Mostly the "switching on a string for different behaviour" bit, and possibly positional "arguments" instead of named keys in an object. Anyway, I can mess around with it on request.

**Comment by damncabbage** [comment]
Do you want this ported over to the newly-released Purescript version?

**Comment by bodil** [comment]
That's probably going to make it get merged faster, at a guess. :)

**Comment by damncabbage** [comment]
@bodil Haha. :smile: I was more asking, "is this a change that you actually want?"

**Comment by bodil** [comment]
Yes, very much. :)

**Comment by damncabbage** [comment]
These tests unfortunately never worked. After three hours I haven't gotten them working. I don't have enough experience to port the test suite in its entirety over to Purescript as per discussion on IRC. Umm. Help. :cold_sweat: 

(As to _why_ the tests don't work, I can't figure out. I thought it was something in the function silently going async, and then the wrapping `run()` calling `done()`, but I really can't pin it down.)

**Comment by hdgarrood** [comment]
Maybe we should leave it for now then, and I might try porting the tests when I get a moment?

PS I looked over the IRC logs, it was me that released purescript-node-path 0.4.1 with the new `Path.parse` function, but I am pretty sure that's ok according to semver, which says that you can do anything you want in 0.x.y releases. And I think this is what we tend to do, at least in core libraries - the second component is for breaking changes, the third is for everything else. Is there a bad consequence of this I'm not aware of?

The `bower.json` definitely specifies at least 0.4.1, so if you had 0.4.0 installed, and `bower install` wasn't updating it, that sounds like bower is misbehaving, right?

**Comment by hdgarrood** [comment]
Ohh - The `bower.json` only specifies `0.4.0`. I forgot to update it. Oops. Will fix that now.

**Comment by bodil** [comment]
True, the Semver spec states that with 0.x versions all bets are more or less off. That's why one should always start at 1.0.0. :)

**Comment by damncabbage** [comment]
The previous (conflicted) commit with the tests: 8160b10

**Comment by damncabbage** [comment]
:rewind:  Okay, ported this branch over to Purescript. :-)

**Comment by damncabbage** [comment]
Revisited the tests; got them working with a `for (…)` cheat, instead of my earlier `forEach(…)` attempt. :wink:

File: test-js/integration.js [hunk 1]
```diff
@@ -58,17 +59,26 @@ describe("integration tests", function() {
...
-    assert.equal(err.trim(), initWithoutForce);
+    for (var idx in filesToOverwrite) {
+      let file = path.join(temp, filesToOverwrite[idx])
+        , dir  = path.dirname(file)
+      if (!fs.existsSync(dir)) { yield sh(`mkdir ${dir}`); }
+      touch.sync(file);
+      const [_, err] = yield pulp("init", null, { expectedExitCode: 1 });
+      assert.match(err.trim(), initWithoutForce(path.basename(file)));
+      const rm = process.platform === "win32" ? "del" : "rm"
+      yield sh(`${rm} ${file}`);
```
Comment (hdgarrood) [inline test-js/integration.js]: Could this use `fs.unlinkSync`?

File: test-js/integration.js [hunk 2]
```diff
@@ -58,17 +59,26 @@ describe("integration tests", function() {
   }));
 
   it("refuses to init without --force", run(function*(sh, pulp, assert, temp) {
-    touch.sync(path.join(temp, "bower.json"));
-    const [_, err] = yield pulp("init", null, { expectedExitCode: 1 });
-    assert.equal(err.trim(), initWithoutForce);
+    for (var idx in filesToOverwrite) {
+      let file = path.join(temp, filesToOverwrite[idx])
+        , dir  = path.dirname(file)
+      if (!fs.existsSync(dir)) { yield sh(`mkdir ${dir}`); }
```
Comment (hdgarrood) [inline test-js/integration.js]: Same here, could this be `fs.mkdirSync`? (I realise I might not have used `fs` absolutely everywhere previously but I think it's probably what we should be doing)

Comment (damncabbage) [inline test-js/integration.js]: Sure; happy to swap these out shortly.

**Comment by hdgarrood** [comment]
@bodil always start at 1.0.0 even if you're expecting to be making breaking changes all the time? (as is usually the case with purescript node bindings)

Anyway, once the `yield sh` stuff is swapped for `fs` stuff, assuming that all works fine, then I think this is good to go.

**Comment by damncabbage** [comment]
Is there any way to force AppVeyor to rebuild without changing the commit? I've hit two sporadic failures on this branch alone. (This last failure: https://ci.appveyor.com/project/bodil/pulp/build/1.0.67; previously it was because a package couldn't downloaded.)

**Comment by hdgarrood** [comment]
There is a rebuild button, but only @bodil can see it.

That specific failure you've linked is really common, maybe half of the appveyor builds fail that way. I don't know if it's a bower bug (race condition?), or appveyor doing something weird, and I don't really want to investigate it, honestly. I'm happy ignoring it, or maybe even turning appveyor off entirely for now.

**Comment by damncabbage** [comment]
Feedback addressed; build passing.
